// This file is generated by news-index.script.ts. Do not edit manually.
import { DatedNewsMetadata } from "@/types/news.types";

const data: DatedNewsMetadata[] = [
  {
    "id": "pioneer-in-university-projects-mentorship",
    "title": "Monark: Pioneer in Supporting Decentralized Accounting University Projects",
    "author": "Marty-Kanatakhatsus Meunier",
    "date": "2020-04-24T04:00:00.000Z",
    "city": "Sherbrooke",
    "source": "https://www.usherbrooke.ca/actualites/nouvelles/sciences-innovations-technologiques/details/42749",
    "image": "./pioneer-in-university-projects-mentorship.jpg",
    "summary": "Monark, founded by Vincent Grenier, leads in supporting university projects in decentralized technologies, building on successful collaborations like CryptoSys with the University of Sherbrooke. The company offers tailored mentorship to transform academic knowledge into market-ready solutions, fostering innovation and professional skills among students."
  }
];

export default data;
