// This file is generated by news-index.script.ts. Do not edit manually.
import { DatedNewsMetadata } from "@/types/news.types";

const data: DatedNewsMetadata[] = [
  {
    "id": "pioneer-in-university-projects-mentorship",
    "title": "Pionnier de l'accompagnement des projets universitaires en comptabilité décentralisée",
    "author": "Marty-Kanatakhatsus Meunier",
    "date": "2020-04-24T00:00:00.000Z",
    "city": "Sherbrooke, QC, Canada",
    "description": "Fondée par Vincent Grenier, Monark se positionne comme le chef de file de l'accompagnement des projets universitaires en technologies décentralisées. Elle s'appuie sur des collaborations comme CryptoSys, menée avec l'Université de Sherbrooke, et offre aux étudiants un mentorat qui transforme leurs travaux en solutions prêtes pour le marché tout en développant leurs compétences professionnelles.",
    "img": "pioneer-in-university-projects-mentorship.webp",
    "img_alt": "Des étudiants réunis autour d'un ordinateur portable dans un amphithéâtre, en plein travail d'équipe",
    "img_author": "Vitaly Gariev",
    "img_author_src": "https://unsplash.com/photos/8gAbl776pc0",
    "read_time_seconds": 160,
    "tags": [
      "Article",
      "Projet",
      "Impact"
    ],
    "category": "monark"
  },
  {
    "id": "real-world-web3-use-cases-that-aren-t-just-nfts",
    "title": "Le Web3 dans la vraie vie : des usages au-delà des NFT",
    "author": "Équipe Monark",
    "date": "2025-09-11T00:00:00.000Z",
    "city": "Sherbrooke, QC, Canada",
    "description": "Le Web3 ne se résume pas aux NFT. Monnaies locales, chaînes d'approvisionnement traçables, documents notariés, partage sécurisé des données médicales, autant d'usages où la technologie décentralisée crée de la confiance et oblige à rendre des comptes.",
    "img": "real-world-web3-use-cases-that-aren-t-just-nfts.webp",
    "img_alt": "Les chaînes d'approvisionnement sont un des cas d'utilisation importants de la blockchain",
    "img_author": "Bernd Dittrich",
    "img_author_src": "https://unsplash.com/photos/a-large-container-ship-in-a-body-of-water-r1AIp7Vj3Mg",
    "read_time_seconds": 190,
    "tags": [
      "Article",
      "Projet",
      "Impact"
    ],
    "category": "build"
  },
  {
    "id": "smart-contracts-explained-like-you-re-5",
    "title": "Les contrats intelligents expliqués comme si vous aviez 5 ans",
    "author": "Équipe Monark",
    "date": "2025-08-21T00:00:00.000Z",
    "city": "Sherbrooke, QC, Canada",
    "description": "Un contrat intelligent est un programme, inscrit sur une blockchain, qui exécute un accord tout seul. Il se passe d'intermédiaire, mais il coûte cher, manque de souplesse et se corrige mal. Il donne le meilleur de lui-même aux côtés des systèmes traditionnels.",
    "img": "smart-contracts-explained-like-you-re-5.webp",
    "img_alt": "Représentation de la Blockchain",
    "img_author": "Shubham Dhage",
    "img_author_src": "https://unsplash.com/photos/a-group-of-cubes-hanging-from-a-ceiling-MBfYGVsDEp8",
    "read_time_seconds": 270,
    "tags": [
      "Article",
      "Technologie"
    ],
    "category": "explained"
  },
  {
    "id": "trust-from-open-data-to-mathematical-proof",
    "title": "La confiance : de la donnée ouverte à la preuve mathématique",
    "author": "Équipe Monark",
    "date": "2025-08-28T00:00:00.000Z",
    "city": "Sherbrooke, QC, Canada",
    "description": "Les blockchains ont gagné la confiance en rendant tout public, au détriment de la vie privée. Les preuves à divulgation nulle de connaissance permettent au Web3 de vérifier une information sans la révéler, pour des systèmes à la fois responsables et confidentiels.",
    "img": "trust-from-open-data-to-mathematical-proof.webp",
    "img_alt": "Les mathématiques ont résolu l'enjeu de la confiance",
    "img_author": "Brett Jordan",
    "img_author_src": "https://unsplash.com/photos/brown-wooden-blocks-on-white-surface-wW-lhteuK0o",
    "read_time_seconds": 150,
    "tags": [
      "Article",
      "Technologie"
    ],
    "category": "explained"
  },
  {
    "id": "web3-developer-roadmap-and-resources",
    "title": "Feuille de route et ressources pour développer en Web3",
    "author": "Équipe Monark",
    "date": "2025-09-04T00:00:00.000Z",
    "city": "Sherbrooke, QC, Canada",
    "description": "Par où commencer en développement Web3, des notions de base comme la blockchain et la cryptographie aux outils comme Solidity et Hardhat, en passant par l'infrastructure, avec The Graph pour les données, Pinax pour l'hébergement et Midnight Network pour la confidentialité.",
    "img": "web3-developer-roadmap-and-resources.webp",
    "img_alt": "Une feuille de route n'est pas toujours une ligne droite",
    "img_author": "Mark König",
    "img_author_src": "https://unsplash.com/photos/yellow-and-black-arrow-sign-ECGv8s2IPG0",
    "read_time_seconds": 160,
    "tags": [
      "Article",
      "Technologie"
    ],
    "category": "build"
  },
  {
    "id": "web3-revolution-reality",
    "title": "Révolution et réalité du Web3 : un bilan honnête",
    "author": "Équipe Monark",
    "date": "2025-08-14T00:00:00.000Z",
    "city": "Sherbrooke, QC, Canada",
    "description": "Un regard franc de Monark sur le Web3, ce qu'il promettait, là où il déçoit et l'approche concrète que nous adoptons pour qu'il soit adopté durablement.",
    "img": "web3-revolution-reality.webp",
    "img_alt": "Une femme prend la parole pendant une discussion de groupe dans une salle d'atelier bondée",
    "img_author": "Antenna",
    "img_author_src": "https://unsplash.com/photos/cw-cj_nFa14",
    "read_time_seconds": 160,
    "tags": [
      "Article",
      "Orientation",
      "État d'esprit"
    ],
    "category": "beyond-the-hype"
  },
  {
    "id": "what-is-web3-really",
    "title": "Le Web3, au fond, qu'est-ce que c'est ?",
    "author": "Équipe Monark",
    "date": "2025-07-25T00:00:00.000Z",
    "city": "Sherbrooke, QC, Canada",
    "description": "Un regard critique sur le Web3, ses promesses et ses problèmes, pour dissiper quelques idées reçues et donner une vision équilibrée de ce que les technologies décentralisées peuvent vraiment apporter.",
    "img": "what-is-web3-really.webp",
    "img_alt": "Une femme en chandail jaune navigue sur son téléphone à la maison",
    "img_author": "Jakub Żerdzicki",
    "img_author_src": "https://unsplash.com/photos/AvEYas-wFs0",
    "read_time_seconds": 220,
    "tags": [
      "Article",
      "Orientation",
      "État d'esprit"
    ],
    "category": "explained"
  },
  {
    "id": "what-monark-is-building-and-why",
    "title": "Ce que Monark construit, et pourquoi",
    "author": "Équipe Monark",
    "date": "2025-09-25T00:00:00.000Z",
    "city": "Sherbrooke, QC, Canada",
    "description": "Monark relie les universités et l'industrie du Web3 en transformant la recherche étudiante en projets viables. Nous incubons de jeunes projets et avons conçu des outils pour la transparence des chaînes d'approvisionnement et le partage sécurisé des données médicales.",
    "img": "what-monark-is-building-and-why.webp",
    "img_alt": "Monarque posé sur la main",
    "img_author": "Matthias Leistikow",
    "img_author_src": "https://unsplash.com/photos/black-and-yellow-butterfly-on-persons-hand-VmwH8vCgUkY",
    "read_time_seconds": 130,
    "tags": [
      "Article",
      "Orientation",
      "Impact"
    ],
    "category": "monark"
  },
  {
    "id": "what-needs-to-happen-before-web3-becomes-everyday-tech",
    "title": "Ce qu'il faudra pour que le Web3 entre dans notre quotidien",
    "author": "Équipe Monark",
    "date": "2025-09-18T00:00:00.000Z",
    "city": "Sherbrooke, QC, Canada",
    "description": "Le Web3 reste difficile à utiliser, mal encadré par la réglementation et mal compris. Comme l'Internet des débuts, il a besoin d'une meilleure infrastructure, surtout pour les portefeuilles et l'identité, avant que le grand public puisse l'adopter sans effort.",
    "img": "what-needs-to-happen-before-web3-becomes-everyday-tech.webp",
    "img_alt": "Une ville animée, qui bénéficierait grandement de la blockchain",
    "img_author": "Jorge Zhagui",
    "img_author_src": "https://unsplash.com/photos/cars-on-road-between-high-rise-buildings-during-daytime-VYLwdMhhKS0",
    "read_time_seconds": 110,
    "tags": [
      "Article",
      "État d'esprit",
      "Impact"
    ],
    "category": "beyond-the-hype"
  },
  {
    "id": "where-blockchain-shines",
    "title": "Là où la blockchain brille, et là où elle déçoit",
    "author": "Équipe Monark",
    "date": "2025-08-09T00:00:00.000Z",
    "city": "Sherbrooke, QC, Canada",
    "description": "La blockchain a été tour à tour surestimée et sous-estimée. Nous regardons où elle est vraiment utile, et où une solution traditionnelle fait encore mieux l'affaire.",
    "img": "where-blockchain-shines.webp",
    "img_alt": "Deux femmes discutent en marchant dans une allée d'entrepôt, l'une tenant une planchette à pince",
    "img_author": "Centre for Ageing Better",
    "img_author_src": "https://unsplash.com/photos/ZlOlRnWk8zU",
    "read_time_seconds": 170,
    "tags": [
      "Article",
      "Orientation",
      "État d'esprit"
    ],
    "category": "beyond-the-hype"
  },
  {
    "id": "who-is-web3-actually-for",
    "title": "À qui le Web3 s'adresse-t-il vraiment ?",
    "author": "Équipe Monark",
    "date": "2025-09-30T00:00:00.000Z",
    "city": "Sherbrooke, QC, Canada",
    "description": "Le Web3 promet un Internet qui appartient à ses utilisateurs, mais pour l'instant cette promesse touche surtout les passionnés de crypto. Pour aller plus loin, il doit répondre à des besoins réels, comme la traçabilité pour les agriculteurs ou des diplômes vérifiables pour les étudiants.",
    "img": "who-is-web3-actually-for.webp",
    "img_alt": "Personnes dans une œuvre d'art interactive",
    "img_author": "Note Thanun",
    "img_author_src": "https://unsplash.com/photos/a-group-of-people-standing-in-a-blue-room-zNzzulArQdc",
    "read_time_seconds": 140,
    "tags": [
      "Article",
      "Orientation",
      "État d'esprit"
    ],
    "category": "beyond-the-hype"
  },
  {
    "id": "why-decentralization-matters",
    "title": "Pourquoi la décentralisation compte, au-delà de l'effet de mode",
    "author": "Équipe Monark",
    "date": "2025-08-02T00:00:00.000Z",
    "city": "Sherbrooke, QC, Canada",
    "description": "Les géants de la technologie et les gardiens institutionnels contrôlent une grande partie de notre vie numérique. La décentralisation change la façon de concevoir et de gouverner les systèmes numériques, et chez Monark, nous explorons les applications concrètes qu'elle peut rendre possibles, en étroite collaboration avec les universités et les écosystèmes décentralisés les plus avancés.",
    "img": "why-decentralization-matters.webp",
    "img_alt": "Des personnes assises en cercle sur des chaises dans un parc, pour une discussion ouverte",
    "img_author": "Dorota Trzaska",
    "img_author_src": "https://unsplash.com/photos/1tAtO-9HYNM",
    "read_time_seconds": 190,
    "tags": [
      "Article",
      "Orientation",
      "État d'esprit"
    ],
    "category": "explained"
  }
];

export default data;
