// This file is generated by project-index.script.ts. Do not edit manually.
import { DatedProjectMetadata } from "@/types/project.types";
export const en: DatedProjectMetadata[] = [
  {
    "id": "access-tokens-pay-per-access-contracts",
    "title": "Access Tokens (Pay-Per-Access Contracts)",
    "description": "Create smart contracts that grant time-based or one-time access to digital or physical content. Users can pay in tokens to unlock a livestream, document, video, or even a smart lock for a room or vault. The contract tracks duration, access rights, and expiration. You can expand this to marketing tools like paid alerts for communities or digital ad banners.",
    "status": "idea",
    "complexity_score": 6,
    "effort_score": -1,
    "adoption_score": 3,
    "blockchain_score": 4,
    "revenue_score": -1,
    "industry_tags": [
      "Services",
      "Media",
      "Entertainment and Sport"
    ],
    "keyword_tags": [
      "Access Control",
      "Tokenization",
      "Wallet Integration",
      "Pay-Per-Access",
      "Smart Contracts"
    ],
    "hash": "fbd0c4c142a0c6d8ac0d5eb99a8d6c3d482669e064c884504b7eb5fe88869ae8",
    "last_updated": "2025-06-06"
  },
  {
    "id": "accounting-blockchain-data-extraction",
    "title": "Accounting blockchain data extraction",
    "description": "Create a tool that extracts, cleans, and formats blockchain transaction data into accounting-ready formats. Users can input a wallet address and receive categorized income/expenses, gas fees, and timestamps. Useful for DAOs, freelancers, and businesses needing audit trails or tax reports. You can use The Graph, APIs, or indexers to feed the data.",
    "status": "idea",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": 8,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Finance and Insurance",
      "Services"
    ],
    "keyword_tags": [
      "Accounting",
      "Audit",
      "Reporting",
      "Data Extraction",
      "Compliance"
    ],
    "hash": "8a4018452bda7173696ad05d6583a6597fc63167769b58b3bf30905a75eeb3de",
    "last_updated": "2025-06-06"
  },
  {
    "id": "address-review-system",
    "title": "Address Review System",
    "description": "Build a decentralized review system where users can submit reviews tied to their wallet addresses. Each review (rating, comment, timestamp) is stored immutably on-chain, ensuring transparency and preventing deletion or manipulation. Useful for evaluating sellers, contributors, or service providers in Web3 ecosystems. Add features like filtering by address, sentiment analysis, or integration with NFT platforms and DAOs.",
    "status": "idea",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 3,
    "blockchain_score": 4,
    "revenue_score": -1,
    "industry_tags": [
      "Services",
      "Digital Communications"
    ],
    "keyword_tags": [
      "Reviews",
      "Transparency",
      "Wallet",
      "Reputation",
      "DAO"
    ],
    "hash": "cfce6203e3723350a3039c721795648e93e0165b40c85c552cf88754d45f853e",
    "last_updated": "2025-06-06"
  },
  {
    "id": "bounty-system",
    "title": "Bounty System",
    "description": "Develop a decentralized platform for task bounties. Users post tasks with deadlines and rewards, contributors submit work, and admins or voters validate the result before payout. Useful for open-source projects, student challenges, or DAO task distribution. Includes smart contract logic and a dashboard for browsing, submitting, and tracking.",
    "status": "prototype",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 3,
    "blockchain_score": 7,
    "revenue_score": -1,
    "industry_tags": [
      "Services",
      "Digital Communications"
    ],
    "keyword_tags": [
      "Bounties",
      "Tasks",
      "Contributors",
      "Incentives",
      "DAO"
    ],
    "hash": "136227327cb3d51c3eb7e4fb4a0e84411efd16f90b25c8c6feb8b9aef7e24e3e",
    "last_updated": "2025-06-06"
  },
  {
    "id": "cadastrum",
    "title": "Cadastrum",
    "description": "A decentralized land and building registry where users can submit and update the physical location, construction year, and modifications of buildings on land parcels. This enables transparent, time-stamped tracking of structures and helps identify regulatory compliance or violations over time.",
    "status": "idea",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": 2,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Cities",
      "Real Estate and Rental",
      "Leasing",
      "Construction"
    ],
    "keyword_tags": [
      "Registry",
      "Mapping",
      "Transparency",
      "Compliance",
      "Buildings"
    ],
    "hash": "1c637bba29c902b6563d61431955b4b6edaf1831d973dfcf05b08ba2eea29236",
    "last_updated": "2025-06-06"
  },
  {
    "id": "contact-list",
    "title": "Contact List",
    "description": "Build a decentralized contact manager that allows users to save and tag wallet addresses with notes, reputation scores, and categories. Contacts are stored locally or on-chain/IPFS, and could include verification status. Useful for DAOs, communities, or marketplaces where trusted contributor tracking is essential. This tool should be easily integratable into other apps so that many apps can share the same contact list. We should be able to have a contact log of all our own addresses and purposes and all of our friends, and businesses contacts addresses.",
    "status": "idea",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 8,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Digital Communications",
      "Services"
    ],
    "keyword_tags": [
      "Identity",
      "Wallet",
      "Tagging",
      "Reputation",
      "Contacts"
    ],
    "hash": "d2bfa9e3c1447a18fad111577f0f7a07c4ead1076f50ce9e061dbc797f51e073",
    "last_updated": "2025-06-06"
  },
  {
    "id": "dao-voting-platform",
    "title": "DAO Voting Platform",
    "description": "Develop a decentralized governance platform that enables token- or wallet-based voting on proposals. Users can submit ideas, cast votes, and track results. Features include quorum logic, delegation, live results, and optional execution hooks. Ideal for DAOs, student orgs, or cooperatives. This is a foundational block for on-chain decision-making.",
    "status": "idea",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 5,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Cities",
      "Services"
    ],
    "keyword_tags": [
      "DAO",
      "Governance",
      "Voting",
      "Proposals",
      "Transparency"
    ],
    "hash": "326953f2622f5ac6a2b1efeb16ca8d614f307a039c00eb1338d648f5aa6ebb64",
    "last_updated": "2025-06-06"
  },
  {
    "id": "defi-borrow",
    "title": "DeFi Borrow",
    "description": "Focus on the borrowing experience in a DeFi protocol. Users request loans, submit collateral, and monitor repayment status. Collateral is locked in smart contracts, and loan terms (APR, expiration) are automatically enforced. Partner with existing testnet lending pools or simulate locally.",
    "status": "idea",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": -1,
    "blockchain_score": -1,
    "revenue_score": -1,
    "industry_tags": [
      "Finance and Insurance",
      "Banking and Capital Markets"
    ],
    "keyword_tags": [
      "Borrowing",
      "DeFi",
      "Collateral",
      "Protocol",
      "Liquidity"
    ],
    "hash": "092b02d9f94515d1cd35d79bd1c4821e1462baa23996127152d770b805315df3",
    "last_updated": "2025-06-06"
  },
  {
    "id": "defi-lending",
    "title": "DeFi Lending",
    "description": "Create a protocol where users supply tokens to liquidity pools in exchange for interest. Manage pool size, utilization rate, and reward logic. Visualize returns over time and integrate with borrow contracts if desired. An excellent way to teach lending mechanics, risk pooling, and token incentives.",
    "status": "idea",
    "complexity_score": 8,
    "effort_score": -1,
    "adoption_score": -1,
    "blockchain_score": -1,
    "revenue_score": -1,
    "industry_tags": [
      "Finance and Insurance",
      "Investing"
    ],
    "keyword_tags": [
      "Lending",
      "DeFi",
      "Yield",
      "Treasury",
      "Liquidity"
    ],
    "hash": "83fa6f9dd127d99ece516e7e9e47f0ca3a50dfcdb319b1b789a958d6b078c8f2",
    "last_updated": "2025-06-06"
  },
  {
    "id": "defi-loans",
    "title": "DeFi Loans",
    "description": "Develop a lending platform where users deposit collateral and borrow tokens. Smart contracts manage interest, health ratios, and liquidations. Useful to simulate MakerDAO-style loans on testnet. Can include dashboards, alerts, and repayment logic. Emphasizes DeFi risk management and user experience.",
    "status": "idea",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": -1,
    "blockchain_score": -1,
    "revenue_score": -1,
    "industry_tags": [
      "Finance and Insurance",
      "Banking and Capital Markets"
    ],
    "keyword_tags": [
      "Lending",
      "Loans",
      "Collateral",
      "DeFi",
      "Automation"
    ],
    "hash": "1a6b687b781780bade78fa7f4e281892777f83b74f4ef52675e2e5b87cbc916c",
    "last_updated": "2025-06-06"
  },
  {
    "id": "defi-swaps",
    "title": "DeFi Swaps",
    "description": "Create a decentralized token swap platform using Automated Market Maker (AMM) principles. Users can swap testnet tokens via liquidity pools and view simulated price impact and slippage. Includes swap UI, liquidity pool logic, and optional fee mechanics. Inspired by platforms like Uniswap.",
    "status": "idea",
    "complexity_score": 8,
    "effort_score": -1,
    "adoption_score": -1,
    "blockchain_score": -1,
    "revenue_score": -1,
    "industry_tags": [
      "Finance and Insurance",
      "Banking and Capital Markets"
    ],
    "keyword_tags": [
      "DeFi",
      "Swap",
      "AMM",
      "Trading",
      "Liquidity"
    ],
    "hash": "93eaf672eba1077c14005e743ab6934a1b0636bcd5cff0f86fc0951ee87f4da1",
    "last_updated": "2025-06-06"
  },
  {
    "id": "digital-will",
    "title": "Digital Will",
    "description": "Create a secure blockchain-based inheritance system. Users set up a digital will where funds are released to beneficiaries based on an on-chain permission system consisting of various user keys or conditions like time delays, inactivity, or third-party validation. Include wallet-based identity, account creation tool, optional social recovery, and contract customization. This ensures irreversible execution and removes the need for centralized estate services.",
    "status": "idea",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": 5,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Finance and Insurance",
      "Services"
    ],
    "keyword_tags": [
      "Inheritance",
      "Smart Contracts",
      "Time Lock",
      "Escrow",
      "Compliance"
    ],
    "hash": "8b7f3e4d83293ba36c70cffde6b2ecba17519bc98800b078fd212fd59de2fa77",
    "last_updated": "2025-06-06"
  },
  {
    "id": "fee-distribution-system",
    "title": "Fee Distribution System",
    "description": "Design a smart contract system that splits incoming payments automatically among stakeholders. Users can define fixed percentages or dynamic formulas. The platform handles income like DAO revenue, royalties, or affiliate payouts and distributes it to multiple wallets upon receipt. Add a UI for configuring, simulating, and tracking earnings transparently.",
    "status": "idea",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 8,
    "blockchain_score": 5,
    "revenue_score": -1,
    "industry_tags": [
      "Finance and Insurance",
      "Banking and Capital Markets"
    ],
    "keyword_tags": [
      "Smart Contracts",
      "Revenue Sharing",
      "Payouts",
      "Treasury",
      "Automation"
    ],
    "hash": "959253c4a144e087bcfad06f4ca8ecf941d315ae147d63aa499fab5e518cdbd5",
    "last_updated": "2025-06-06"
  },
  {
    "id": "guardian",
    "title": "Guardian",
    "description": "Guardian is a mobile Web3 alert app that notifies nearby users in emergencies. Alerts are tied to wallet IDs, and responders receive funds from a pre-funded smart contract pool. This incentivizes real help while discouraging misuse through built-in accountability and rewards.",
    "status": "idea",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": 2,
    "blockchain_score": 2,
    "revenue_score": -1,
    "industry_tags": [
      "Cities",
      "Services",
      "Digital Communications"
    ],
    "keyword_tags": [
      "Access Control",
      "Wallet Integration",
      "Rewards",
      "Smart Contracts",
      "Reputation"
    ],
    "hash": "9c35ce9490b54d5d1eb071ca5c4110f1fcc89e94d13e4f5edff2a6618cb20fda",
    "last_updated": "2025-06-06"
  },
  {
    "id": "inventory-and-sales-for-farm-goods",
    "title": "Inventory and Sales for Farm Goods",
    "description": "Design a decentralized system that allows farmers to manage their inventory and sell fruits and vegetables without being physically present. Buyers scan a code at the self-serve stand, interact with a smart contract to purchase produce, and the system updates available stock. Could include mobile UI, local pricing, availability tracking, and optional reward tokens for buyers. Perfect for rural zones and trustless microtransactions.",
    "status": "idea",
    "complexity_score": 6,
    "effort_score": -1,
    "adoption_score": 1,
    "blockchain_score": 3,
    "revenue_score": -1,
    "industry_tags": [
      "Agriculture",
      "Food and Beverage",
      "Retail"
    ],
    "keyword_tags": [
      "Inventory",
      "Microtransactions",
      "Smart Contracts",
      "QR Code",
      "Access"
    ],
    "hash": "8a733816f7c3ed2ff9391ee8559292fba8e7843848b75a769dc0815863e74b0c",
    "last_updated": "2025-06-06"
  },
  {
    "id": "land-registry-voting",
    "title": "Land Registry Voting",
    "description": "Build a voting system where landowners and/or property tenants can vote on proposals related to their region. Tie voting rights to land ownership (real or simulated), verify votes via wallet signatures, and display results on a map or dashboard. Explore ways to sync on-chain votes with off-chain registries for potential civic integration.",
    "status": "idea",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": 2,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Real Estate and Rental",
      "Leasing",
      "Cities"
    ],
    "keyword_tags": [
      "Land Registry",
      "Voting",
      "Governance",
      "Transparency",
      "Mapping"
    ],
    "hash": "e41bbd753fa2b1b9efc3e1e52eef6616f9d637f9d8524eca23dac6796e523299",
    "last_updated": "2025-06-06"
  },
  {
    "id": "milestone-based-smart-contracts-and-escrow",
    "title": "Milestone-Based Smart Contracts and Escrow",
    "description": "Design contracts that hold funds and release them gradually based on progress. Each milestone is defined upfront with conditions for approval. Think construction contracts, grants, or dev work. Funds unlock when a milestone is validated by the client and/or third-party oracle. Add review flows and progress visualization.",
    "status": "idea",
    "complexity_score": 6,
    "effort_score": -1,
    "adoption_score": 4,
    "blockchain_score": 5,
    "revenue_score": -1,
    "industry_tags": [
      "Construction",
      "Services"
    ],
    "keyword_tags": [
      "Milestones",
      "Smart Contracts",
      "Escrow",
      "Funding",
      "Automation"
    ],
    "hash": "d20a8cbfa974f7e16e375d26210f4cc499a7671a51871788436e4dc26b5e9571",
    "last_updated": "2025-06-06"
  },
  {
    "id": "multichain-portfolio-tracker",
    "title": "Multichain Portfolio Tracker",
    "description": "Build a dashboard that aggregates a user's holdings across multiple blockchains. Show token balances, NFTs, and historical activity using APIs or RPCs the supported blockchains. Add filtering, wallet tagging, asset valuation, and graphs. This helps users view their Web3 footprint in one place.",
    "status": "idea",
    "complexity_score": 7,
    "effort_score": 9,
    "adoption_score": 3,
    "blockchain_score": 5,
    "revenue_score": -1,
    "industry_tags": [
      "Investing",
      "Finance and Insurance"
    ],
    "keyword_tags": [
      "Portfolio",
      "Analytics",
      "Tracking",
      "Wallet",
      "Dashboard"
    ],
    "hash": "b71e4df98f6d0e98a7096e4dabbc11e09aeb418a438d2a0d1b73d62be185d111",
    "last_updated": "2025-06-06"
  },
  {
    "id": "nft-ticketing-platform",
    "title": "NFT Ticketing Platform",
    "description": "Build a full-stack NFT ticketing platform where organizers mint unique event tickets as NFTs. Tickets include metadata (seat, time, access rules, special rewards, etc.), and can be scanned for entry via blockchain wallet signature or QR code. Resale restrictions and secondary royalties are enforced via smart contracts. You can add bonus features like POAP collectibles, attendance badges, or discount perks.",
    "status": "prototype",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": 5,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Media",
      "Entertainment and Sport",
      "Services"
    ],
    "keyword_tags": [
      "NFT",
      "Ticketing",
      "Tokenization",
      "Wallet Integration",
      "Access Control"
    ],
    "hash": "308b7934e37f885539b920eca22b45e9007b32ff0b6964fe4773a122746bc68e",
    "last_updated": "2025-06-06"
  },
  {
    "id": "real-time-royalty-distribution",
    "title": "Real-Time Royalty Distribution",
    "description": "Develop a system that automatically distributes revenue (e.g., from music streams, NFT sales, or services) in real time among multiple recipients. Use smart contracts to define splits (%), track flows, and release funds regularly or continuously. Combine with streaming protocols (like Superfluid) or build your own flow mechanism.",
    "status": "idea",
    "complexity_score": 6,
    "effort_score": -1,
    "adoption_score": 3,
    "blockchain_score": 4,
    "revenue_score": -1,
    "industry_tags": [
      "Media",
      "Entertainment and Sport",
      "Finance and Insurance"
    ],
    "keyword_tags": [
      "Royalties",
      "Automation",
      "Smart Contracts",
      "Revenue",
      "Content"
    ],
    "hash": "81278d93994e2f52f1ac85685bf3299fcb5626368e0042e8544a70dd930d539e",
    "last_updated": "2025-06-06"
  },
  {
    "id": "referral-system",
    "title": "Referral System",
    "description": "Build a referral engine that tracks wallet-to-wallet invitations and rewards activity-based outcomes (e.g., app sign-ups, task completions). Smart contracts store who referred whom, trigger rewards when milestones are hit, and prevent abuse. Perfect for ambassador programs or affiliate networks. Includes dashboards for tracking performance.",
    "status": "idea",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 8,
    "blockchain_score": 5,
    "revenue_score": -1,
    "industry_tags": [
      "Services",
      "Media",
      "Entertainment and Sport"
    ],
    "keyword_tags": [
      "Referral",
      "Incentives",
      "Wallet",
      "Tracking",
      "Engagement"
    ],
    "hash": "8cc7adbe80b05b4ff6d61a3331c83356672b680ee9828281c1a578145eaa952e",
    "last_updated": "2025-06-06"
  },
  {
    "id": "supply-chain-tracking",
    "title": "Supply Chain Tracking",
    "description": "Develop a blockchain based application that records each step of a product's journey on-chain. Every iot sensor and actor (producer, shipper, vendor) logs actions on-chain to create a tamper-proof, traceable history. Smart contracts verify transactions and time-stamp checkpoints. This system ensures authenticity, combats fraud, and enhances transparency in many industries such as food, construction, pharma, etc.",
    "status": "idea",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 8,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Agriculture",
      "Food and Beverage",
      "Cities",
      "Retail"
    ],
    "keyword_tags": [
      "Traceability",
      "Transparency",
      "Smart Contracts",
      "Automation",
      "Mapping"
    ],
    "hash": "19d97c898f1090f6ad3990a5933618f4ce85cebfb094633d8f4907db157ece28",
    "last_updated": "2025-06-06"
  },
  {
    "id": "systems-for-co-ops",
    "title": "Systems for Co-ops",
    "description": "Create a modular system for digital cooperatives with a big focus on accessibility and ease of use. Members join via wallet, vote on proposals, and manage shared resources and finances. Include a treasury dashboard, proposal history, and access roles. Designed for groups that want to operate transparently and democratically without centralized software. Could simulate DAO-like operations with real-world use cases.",
    "status": "idea",
    "complexity_score": 8,
    "effort_score": -1,
    "adoption_score": 1,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Cities",
      "Services"
    ],
    "keyword_tags": [
      "Co-op",
      "DAO",
      "Incentives",
      "Treasury",
      "Governance"
    ],
    "hash": "6ca2a1893b03032ea147b9024be81562c942f941eee075ffcbf6d926cfd562c7",
    "last_updated": "2025-06-06"
  },
  {
    "id": "time-locked-contracts",
    "title": "Time Locked Contracts",
    "description": "Implement smart contracts that release funds or privileges only after a set time. Use cases include vesting periods, delayed payments, subscriptions, or digital wills. Include a dashboard where users define recipients, amounts, and time delays. This teaches foundational concepts like block time, escrow, and release conditions.",
    "status": "idea",
    "complexity_score": 4,
    "effort_score": -1,
    "adoption_score": 5,
    "blockchain_score": 5,
    "revenue_score": -1,
    "industry_tags": [
      "Finance and Insurance",
      "Services"
    ],
    "keyword_tags": [
      "Time Lock",
      "Smart Contracts",
      "Escrow",
      "Automation",
      "Vesting"
    ],
    "hash": "83dee9cbd3b182f5ec2e610ca4a0f82ebe5a3b51aa4858aa8da82b863745d920",
    "last_updated": "2025-06-06"
  },
  {
    "id": "web3-signatures",
    "title": "Web3 Signatures",
    "description": "Create a system where users sign documents or transactions using their wallet signature. Store document hashes on-chain, and optionally save files on IPFS. Others can verify the timestamp, signer identity, and content integrity. Mimics tools like DocuSign but using blockchain authentication that are decentralized and censorship-resistant.",
    "status": "idea",
    "complexity_score": 4,
    "effort_score": -1,
    "adoption_score": 3,
    "blockchain_score": 7,
    "revenue_score": -1,
    "industry_tags": [
      "Services",
      "Banking and Capital Markets"
    ],
    "keyword_tags": [
      "Signature",
      "Authentication",
      "IPFS",
      "Compliance",
      "Documents"
    ],
    "hash": "eda671dd7ce50abd38087b0455175bd7528bf0f3cc05daa1b18c57d4fd7cee36",
    "last_updated": "2025-06-06"
  }
];


export const fr: DatedProjectMetadata[] = [
  {
    "id": "access-tokens-pay-per-access-contracts",
    "title": "Jetons d'Accès (Contrats Pay-Per-Access)",
    "description": "Créez des contrats intelligents qui accordent un accès basé sur le temps ou à usage unique à du contenu numérique ou physique. Les utilisateurs peuvent payer en jetons pour déverrouiller une diffusion en direct, un document, une vidéo, ou même une serrure intelligente pour une salle ou un coffre-fort. Le contrat suit la durée, les droits d'accès, et l'expiration. Vous pouvez étendre ceci à des outils de marketing comme des alertes payantes pour les communautés ou des bannières publicitaires numériques.",
    "status": "idea",
    "complexity_score": 6,
    "effort_score": -1,
    "adoption_score": 3,
    "blockchain_score": 4,
    "revenue_score": -1,
    "industry_tags": [
      "Services",
      "Média",
      "Divertissement et sport"
    ],
    "keyword_tags": [
      "Contrôle d'accès",
      "Tokenisation",
      "Portefeuille",
      "Pay-Per-Access",
      "Contrats intelligents"
    ],
    "hash": "3c0d7536c946fae4e665802e4ae9df8443e750e6b6f6b5b18774de782d6630ac",
    "last_updated": "2025-06-06"
  },
  {
    "id": "accounting-blockchain-data-extraction",
    "title": "Extraction de données comptables de blockchain",
    "description": "Créez un outil qui extrait, nettoie et formate les données de transaction blockchain en formats prêts pour la comptabilité. Les utilisateurs peuvent entrer une adresse de portefeuille et recevoir des revenus/dépenses catégorisés, des frais de gaz et des horodatages. Utile pour les DAO, les indépendants et les entreprises nécessitant des audits ou des rapports fiscaux. Vous pouvez utiliser The Graph, APIs, ou des indexeurs pour nourrir les données.",
    "status": "idée",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": 8,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Finance et assurance",
      "Services"
    ],
    "keyword_tags": [
      "Comptabilité",
      "Audit",
      "Reporting",
      "Extraction de données",
      "Conformité"
    ],
    "hash": "563c80f3a05495776235444898b1c158f061342ed4be1184b4cde7387ef62218",
    "last_updated": "2025-06-06"
  },
  {
    "id": "address-review-system",
    "title": "Address Review System",
    "description": "Build a decentralized review system where users can submit reviews tied to their wallet addresses. Each review (rating, comment, timestamp) is stored immutably on-chain, ensuring transparency and preventing deletion or manipulation. Useful for evaluating sellers, contributors, or service providers in Web3 ecosystems. Add features like filtering by address, sentiment analysis, or integration with NFT platforms and DAOs.",
    "status": "idea",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 3,
    "blockchain_score": 4,
    "revenue_score": -1,
    "industry_tags": [
      "Services",
      "Communications numériques"
    ],
    "keyword_tags": [
      "Reviews",
      "Transparence",
      "Portefeuille",
      "Réputation",
      "DAO"
    ],
    "hash": "8b92ac08bec0b5fa805b285b53680a679c6e0c0426e3aa722c51e1f8d5668b34",
    "last_updated": "2025-06-06"
  },
  {
    "id": "bounty-system",
    "title": "Système de primes",
    "description": "Développez une plateforme décentralisée pour les primes de tâches. Les utilisateurs publient des tâches avec des échéances et des récompenses, les contributeurs soumettent des travaux, et les administrateurs ou les votants valident le résultat avant le paiement. Utile pour les projets open source, les défis étudiants, ou la distribution de tâches DAO. Comprend une logique de contrat intelligent et un tableau de bord pour parcourir, soumettre et suivre.",
    "status": "prototype",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 3,
    "blockchain_score": 7,
    "revenue_score": -1,
    "industry_tags": [
      "Services",
      "Communications numériques"
    ],
    "keyword_tags": [
      "Primes",
      "Tâches",
      "Contributeurs",
      "Incitations",
      "DAO"
    ],
    "hash": "36c2e40abda3c09f0a03c2a5e258b30270de4f0a52c358455400a121625ce54b",
    "last_updated": "2025-06-06"
  },
  {
    "id": "cadastrum",
    "title": "Cadastrum",
    "description": "Un registre décentralisé des terrains et des bâtiments où les utilisateurs peuvent soumettre et mettre à jour l'emplacement physique, l'année de construction et les modifications des bâtiments sur des parcelles de terrain. Cela permet un suivi transparent et horodaté des structures et aide à identifier la conformité réglementaire ou les violations au fil du temps.",
    "status": "idea",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": 2,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Villes",
      "Immobilier et location",
      "Bail",
      "Construction"
    ],
    "keyword_tags": [
      "Registre",
      "Cartographie",
      "Transparence",
      "Conformité",
      "Bâtiments"
    ],
    "hash": "17d0ea96937d2536654985df7dd772a5cc0eb0db6f18f05455230aba8f03e20b",
    "last_updated": "2025-06-06"
  },
  {
    "id": "contact-list",
    "title": "Liste de Contacts",
    "description": "Construisez un gestionnaire de contacts décentralisé qui permet aux utilisateurs de sauvegarder et de taguer les adresses de portefeuilles avec des notes, des scores de réputation et des catégories. Les contacts sont stockés localement ou sur la chaîne/IPFS, et pourraient inclure le statut de vérification. Utile pour les DAO, les communautés ou les marchés où le suivi des contributeurs de confiance est essentiel. Cet outil doit être facilement intégrable dans d'autres applications afin que de nombreuses applications puissent partager la même liste de contacts. Nous devrions être en mesure d'avoir un registre de contact de toutes nos propres adresses et objectifs et de tous nos amis, et des adresses de contacts d'entreprises.",
    "status": "idée",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 8,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Communications numériques",
      "Services"
    ],
    "keyword_tags": [
      "Identité",
      "Portefeuille",
      "Étiquetage",
      "Réputation",
      "Contacts"
    ],
    "hash": "752b4d393d7c7404ea33a42a6ce40dd586ed9b6def747f56b59d1f599aba7cc2",
    "last_updated": "2025-06-06"
  },
  {
    "id": "dao-voting-platform",
    "title": "Plateforme de Vote DAO",
    "description": "Développez une plateforme de gouvernance décentralisée qui permet le vote basé sur les jetons ou les portefeuilles pour des propositions. Les utilisateurs peuvent soumettre des idées, voter, et suivre les résultats. Les fonctionnalités comprennent la logique du quorum, la délégation, les résultats en direct, et des crochets d'exécution optionnels. Idéal pour les DAOs, les organisations étudiantes, ou les coopératives. Il s'agit d'un bloc d'élément fondamental pour la prise de décision on-chain.",
    "status": "idée",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 5,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Villes",
      "Services"
    ],
    "keyword_tags": [
      "DAO",
      "Gouvernance",
      "Vote",
      "Propositions",
      "Transparence"
    ],
    "hash": "f14d0aa628c9b1328241b24a853c36521ea5ba48b7d30fe8d5fc9b2413430f3f",
    "last_updated": "2025-06-06"
  },
  {
    "id": "defi-borrow",
    "title": "DeFi Emprunt",
    "description": "Concentrez-vous sur l'expérience d'emprunt dans un protocole DeFi. Les utilisateurs demandent des prêts, soumettent des garanties et surveillent l'état du remboursement. Les garanties sont verrouillées dans des contrats intelligents, et les conditions de prêt (APR, expiration) sont appliquées automatiquement. Associez-vous à des pools de prêts testnet existants ou simulez localement.",
    "status": "idée",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": -1,
    "blockchain_score": -1,
    "revenue_score": -1,
    "industry_tags": [
      "Finance et assurances",
      "Banques et marchés de capitaux"
    ],
    "keyword_tags": [
      "Emprunt",
      "DeFi",
      "Garantie",
      "Protocole",
      "Liquidité"
    ],
    "hash": "8402e11cb49bc6bd9d5595af4459f4db36d0037189151958700b0ebcb41a0b4c",
    "last_updated": "2025-06-06"
  },
  {
    "id": "defi-lending",
    "title": "Prêt DeFi",
    "description": "Créez un protocole où les utilisateurs fournissent des jetons à des pools de liquidités en échange d'intérêts. Gérez la taille du pool, le taux d'utilisation, et la logique de récompense. Visualisez les rendements dans le temps et intégrez avec des contrats de prêt si vous le souhaitez. Un excellent moyen d'enseigner les mécanismes de prêt, la mutualisation des risques, et les incitations token.",
    "status": "idée",
    "complexity_score": 8,
    "effort_score": -1,
    "adoption_score": -1,
    "blockchain_score": -1,
    "revenue_score": -1,
    "industry_tags": [
      "Finance et assurance",
      "Investissement"
    ],
    "keyword_tags": [
      "Prêts",
      "DeFi",
      "Rendement",
      "Trésorerie",
      "Liquidité"
    ],
    "hash": "e29a67a8fa8cb0cce261ba497a2d75cb3218177851f605ed1ab729f31d857ebd",
    "last_updated": "2025-06-06"
  },
  {
    "id": "defi-loans",
    "title": "Prêts DeFi",
    "description": "Développez une plateforme de prêt où les utilisateurs déposent des garanties et empruntent des tokens. Les contrats intelligents gèrent les intérêts, les ratios de santé et les liquidations. Utile pour simuler des prêts de style MakerDAO sur testnet. Peut inclure des tableaux de bord, des alertes et une logique de remboursement. Met l'accent sur la gestion des risques DeFi et l'expérience utilisateur.",
    "status": "idea",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": -1,
    "blockchain_score": -1,
    "revenue_score": -1,
    "industry_tags": [
      "Finance et assurance",
      "Banques et marchés de capitaux"
    ],
    "keyword_tags": [
      "Prêts",
      "Prêts",
      "Garantie",
      "DeFi",
      "Automatisation"
    ],
    "hash": "c63bf1c7029324aced55c3ce7e10b74a382cb6e7d5d088d94314bc480eaaf8af",
    "last_updated": "2025-06-06"
  },
  {
    "id": "defi-swaps",
    "title": "Swaps DeFi",
    "description": "Créez une plateforme d'échange de tokens décentralisée en utilisant les principes de l'Automated Market Maker (AMM). Les utilisateurs peuvent échanger des tokens de testnet via des pools de liquidité et visualiser l'impact du prix simulé et le glissement. Inclut l'UI de swap, la logique de pool de liquidité, et des mécanismes de frais optionnels. Inspiré par des plateformes comme Uniswap.",
    "status": "idée",
    "complexity_score": 8,
    "effort_score": -1,
    "adoption_score": -1,
    "blockchain_score": -1,
    "revenue_score": -1,
    "industry_tags": [
      "Finance et assurance",
      "Banques et marchés de capitaux"
    ],
    "keyword_tags": [
      "DeFi",
      "Swap",
      "AMM",
      "Trading",
      "Liquidité"
    ],
    "hash": "a9acb7a69ebf23b063e735ae33a1c6d91ae953c163b05f454b5a03d80c6d14d6",
    "last_updated": "2025-06-06"
  },
  {
    "id": "digital-will",
    "title": "Testament Numérique",
    "description": "Créez un système d'héritage basé sur la blockchain sécurisé. Les utilisateurs établissent un testament numérique où les fonds sont libérés aux bénéficiaires en fonction d'un système d'autorisation en chaîne qui consiste en diverses clés d'utilisateur ou conditions telles que des délais, l'inactivité ou la validation de tiers. Inclut l'identité basée sur le portefeuille, l'outil de création de compte, la récupération sociale optionnelle et la personnalisation du contrat. Cela garantit l'exécution irréversible et élimine le besoin de services successorales centralisés.",
    "status": "idée",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": 5,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Finance et assurance",
      "Services"
    ],
    "keyword_tags": [
      "Héritage",
      "Contrats intelligents",
      "Verrouillage temporel",
      "Escrow",
      "Conformité"
    ],
    "hash": "063d846dbebc80982f9be559ba062b0735956cdbb72544a1525b6e04906cf752",
    "last_updated": "2025-06-06"
  },
  {
    "id": "fee-distribution-system",
    "title": "Système de Distribution des Frais",
    "description": "Concevez un système de contrat intelligent qui divise automatiquement les paiements entrants entre les parties prenantes. Les utilisateurs peuvent définir des pourcentages fixes ou des formules dynamiques. La plateforme gère des revenus tels que les revenus de DAO, les royalties ou les paiements d'affiliation et les distribue à plusieurs portefeuilles à réception. Ajoutez une interface utilisateur pour configurer, simuler et suivre les revenus de manière transparente.",
    "status": "idea",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 8,
    "blockchain_score": 5,
    "revenue_score": -1,
    "industry_tags": [
      "Finance et assurance",
      "Banques et marchés de capitaux"
    ],
    "keyword_tags": [
      "Contrats intelligents",
      "Partage de revenus",
      "Paiements",
      "Trésorerie",
      "Automatisation"
    ],
    "hash": "37eadfbe4be96e4b05d0ca10bc5f6e06cd3119ae122e86b313c3e52b723c49c0",
    "last_updated": "2025-06-06"
  },
  {
    "id": "guardian",
    "title": "Guardian",
    "description": "Guardian est une application d'alerte Web3 mobile qui notifie les utilisateurs à proximité en cas d'urgence. Les alertes sont liées aux ID de portefeuille, et les intervenants reçoivent des fonds d'une pool de contrats intelligents préfinancée. Ceci incite à une véritable aide tout en décourageant l'abus grâce à la responsabilité intégrée et aux récompenses.",
    "status": "idée",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": 2,
    "blockchain_score": 2,
    "revenue_score": -1,
    "industry_tags": [
      "Villes",
      "Services",
      "Communications numériques"
    ],
    "keyword_tags": [
      "Contrôle d'accès",
      "Portefeuille",
      "Récompenses",
      "Contrats intelligents",
      "Réputation"
    ],
    "hash": "587076c5cd4fd93cf71b35a92dc36a3f0963d7139f729e3f42010f44136df98b",
    "last_updated": "2025-06-06"
  },
  {
    "id": "inventory-and-sales-for-farm-goods",
    "title": "Inventaire et ventes pour les produits agricoles",
    "description": "Concevez un système décentralisé qui permet aux agriculteurs de gérer leur inventaire et de vendre des fruits et légumes sans être physiquement présents. Les acheteurs scannent un code sur le stand en libre-service, interagissent avec un contrat intelligent pour acheter des produits, et le système met à jour le stock disponible. Cela pourrait inclure une interface mobile, un prix local, le suivi de la disponibilité et des jetons de récompense optionnels pour les acheteurs. Parfait pour les zones rurales et les microtransactions sans confiance.",
    "status": "idée",
    "complexity_score": 6,
    "effort_score": -1,
    "adoption_score": 1,
    "blockchain_score": 3,
    "revenue_score": -1,
    "industry_tags": [
      "Agriculture",
      "Alimentation et boissons",
      "Vente au détail"
    ],
    "keyword_tags": [
      "Inventaire",
      "Microtransactions",
      "Contrats intelligents",
      "Code QR",
      "Accès"
    ],
    "hash": "f4bc6bc5589ae1ab4bd54fcd6c902022ac59ac21d0aa655ee6a25c0d3841999f",
    "last_updated": "2025-06-06"
  },
  {
    "id": "land-registry-voting",
    "title": "Vote du Registre foncier",
    "description": "Construisez un système de vote où les propriétaires fonciers et/ou les locataires de biens immobiliers peuvent voter sur des propositions relatives à leur région. Liez les droits de vote à la propriété foncière (réelle ou simulée), vérifiez les votes par les signatures de portefeuille, et affichez les résultats sur une carte ou un tableau de bord. Explorez les moyens de synchroniser les votes en chaîne avec les registres hors chaîne pour une intégration civique potentielle.",
    "status": "idée",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": 2,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Immobilier et location",
      "Location",
      "Villes"
    ],
    "keyword_tags": [
      "Registre foncier",
      "Vote",
      "Gouvernance",
      "Transparence",
      "Cartographie"
    ],
    "hash": "a880414fe751769faa54248c37b80a1d6e760f2429580bec750f18224f8fb571",
    "last_updated": "2025-06-06"
  },
  {
    "id": "milestone-based-smart-contracts-and-escrow",
    "title": "Contrats intelligents basés sur des jalons et Escrow",
    "description": "Concevez des contrats qui retiennent les fonds et les libèrent progressivement en fonction des progrès. Chaque jalon est défini à l'avance avec des conditions d'approbation. Pensez aux contrats de construction, aux subventions ou au travail de développement. Les fonds se libèrent lorsque un jalon est validé par le client et/ou un oracle tiers. Ajoutez des flux de révision et une visualisation des progrès.",
    "status": "idée",
    "complexity_score": 6,
    "effort_score": -1,
    "adoption_score": 4,
    "blockchain_score": 5,
    "revenue_score": -1,
    "industry_tags": [
      "Construction",
      "Services"
    ],
    "keyword_tags": [
      "Jalons",
      "Contrats intelligents",
      "Escrow",
      "Financement",
      "Automatisation"
    ],
    "hash": "912ba5cb6744e76fed73ad8a0ac8e40cc1c3556b613b056a7ad0586344115872",
    "last_updated": "2025-06-06"
  },
  {
    "id": "multichain-portfolio-tracker",
    "title": "Suivi de Portfolio Multichain",
    "description": "Créez un tableau de bord qui agrège les avoirs d'un utilisateur sur plusieurs blockchains. Affichez les soldes de jetons, NFTs, et l'activité historique en utilisant les API ou RPC des blockchains supportées. Ajoutez des filtres, un étiquetage de portefeuille, l'évaluation des actifs et des graphiques. Cela aide les utilisateurs à visualiser leur empreinte Web3 en un seul endroit.",
    "status": "idée",
    "complexity_score": 7,
    "effort_score": 9,
    "adoption_score": 3,
    "blockchain_score": 5,
    "revenue_score": -1,
    "industry_tags": [
      "Investissement",
      "Finance et assurance"
    ],
    "keyword_tags": [
      "Portefeuille",
      "Analytique",
      "Suivi",
      "Portefeuille",
      "Tableau de bord"
    ],
    "hash": "d3234b3e40ed14c54a024c4f3556e134bcd0ca8d31734256ad3ea37b469191c9",
    "last_updated": "2025-06-06"
  },
  {
    "id": "nft-ticketing-platform",
    "title": "Plateforme de billetterie NFT",
    "description": "Développez une plateforme de billetterie NFT complète où les organisateurs créent des billets d'événement uniques sous forme de NFT. Les billets incluent des métadonnées (siège, heure, règles d'accès, récompenses spéciales, etc.) et peuvent être scannés pour l'entrée via une signature de portefeuille blockchain ou un code QR. Les restrictions de revente et les redevances secondaires sont appliquées via des contrats intelligents. Vous pouvez ajouter des fonctionnalités bonus comme des POAP à collectionner, des badges de présence ou des avantages de réduction.",
    "status": "prototype",
    "complexity_score": 7,
    "effort_score": -1,
    "adoption_score": 5,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Médias",
      "Divertissement et sport",
      "Services"
    ],
    "keyword_tags": [
      "NFT",
      "Billetterie",
      "Tokenisation",
      "Portefeuille",
      "Contrôle d'accès"
    ],
    "hash": "a6ef59358308b35e2ec87ba8a619c91c50cca14c1313fe5e6f4f4edbcb53ed3f",
    "last_updated": "2025-06-06"
  },
  {
    "id": "real-time-royalty-distribution",
    "title": "Distribution de Royautés en Temps Réel",
    "description": "Développez un système qui distribue automatiquement les revenus (par exemple, de flux musicaux, ventes de NFT ou services) en temps réel parmi plusieurs destinataires. Utilisez des contrats intelligents pour définir les divisions (%), suivre les flux et libérer régulièrement ou continuellement des fonds. Combinez avec des protocoles de streaming (comme Superfluid) ou construisez votre propre mécanisme de flux.",
    "status": "idée",
    "complexity_score": 6,
    "effort_score": -1,
    "adoption_score": 3,
    "blockchain_score": 4,
    "revenue_score": -1,
    "industry_tags": [
      "Médias",
      "Divertissement et sport",
      "Finance et assurance"
    ],
    "keyword_tags": [
      "Royautés",
      "Automatisation",
      "Contrats intelligents",
      "Revenus",
      "Contenu"
    ],
    "hash": "408713d0e8e9f1692c5c44113ab6375dd4ca20a73360de0f3154e0ac5962da4e",
    "last_updated": "2025-06-06"
  },
  {
    "id": "referral-system",
    "title": "Système de Parrainage",
    "description": "Construisez un moteur de parrainage qui suit les invitations de portefeuille à portefeuille et récompense les résultats basés sur l'activité (par exemple, les inscriptions à l'application, les réalisations de tâches). Les contrats intelligents stockent qui a parrainé qui, déclenchent des récompenses lorsque des étapes sont atteintes et préviennent les abus. Parfait pour les programmes d'ambassadeurs ou les réseaux d'affiliés. Comprend des tableaux de bord pour suivre les performances.",
    "status": "idée",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 8,
    "blockchain_score": 5,
    "revenue_score": -1,
    "industry_tags": [
      "Services",
      "Médias",
      "Divertissement et sport"
    ],
    "keyword_tags": [
      "Parrainage",
      "Incitations",
      "Portefeuille",
      "Suivi",
      "Engagement"
    ],
    "hash": "4b9cdefb749721e564a274d5a5e649c6214c4c2ba08c9f5258d59958d6812653",
    "last_updated": "2025-06-06"
  },
  {
    "id": "supply-chain-tracking",
    "title": "Suivi de la Chaîne d'Approvisionnement",
    "description": "Développez une application basée sur la blockchain qui enregistre chaque étape du voyage d'un produit sur la chaîne. Chaque capteur et acteur IoT (producteur, expéditeur, vendeur) enregistre des actions sur la chaîne pour créer un historique inviolable et traçable. Les smart contracts vérifient les transactions et tamponnent les points de contrôle. Ce système assure l'authenticité, combat la fraude et améliore la transparence dans de nombreuses industries telles que l'alimentation, la construction, la pharma, etc.",
    "status": "idée",
    "complexity_score": 5,
    "effort_score": -1,
    "adoption_score": 8,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Agriculture",
      "Alimentation et boissons",
      "Villes",
      "Retail"
    ],
    "keyword_tags": [
      "Traçabilité",
      "Transparence",
      "Contrats intelligents",
      "Automatisation",
      "Cartographie"
    ],
    "hash": "b22e93ae91529b6af9cdfe25e09dd0521f71fbb3eca37bd9fe3ec4e5b0f81e6b",
    "last_updated": "2025-06-06"
  },
  {
    "id": "systems-for-co-ops",
    "title": "Systèmes pour Coopératives",
    "description": "Créer un système modulaire pour les coopératives numériques avec un grand accent sur l'accessibilité et la facilité d'utilisation. Les membres rejoignent via un portefeuille, votent sur les propositions et gèrent les ressources et les finances partagées. Inclure un tableau de bord du trésor, l'historique des propositions et les rôles d'accès. Conçu pour les groupes qui veulent opérer de manière transparente et démocratique sans logiciel centralisé. Pourrait simuler des opérations comme DAO avec des cas d'utilisation réels.",
    "status": "idée",
    "complexity_score": 8,
    "effort_score": -1,
    "adoption_score": 1,
    "blockchain_score": 8,
    "revenue_score": -1,
    "industry_tags": [
      "Villes",
      "Services"
    ],
    "keyword_tags": [
      "Coopérative",
      "DAO",
      "Incitations",
      "Trésorerie",
      "Gouvernance"
    ],
    "hash": "22f98ed18c034c6cc0076d34e4e75c9b5a77d581ce39eefccc18c24401dd89fa",
    "last_updated": "2025-06-06"
  },
  {
    "id": "time-locked-contracts",
    "title": "Contrats à échéance",
    "description": "Mettez en œuvre des contrats intelligents qui libèrent des fonds ou des privilèges uniquement après un délai défini. Les cas d'utilisation incluent les périodes de vesting, les paiements différés, les abonnements ou les testaments numériques. Inclure un tableau de bord où les utilisateurs définissent les destinataires, les montants et les délais. Cela enseigne des concepts fondamentaux comme le temps de blocage, l'escrow, et les conditions de libération.",
    "status": "idea",
    "complexity_score": 4,
    "effort_score": -1,
    "adoption_score": 5,
    "blockchain_score": 5,
    "revenue_score": -1,
    "industry_tags": [
      "Finance et assurance",
      "Services"
    ],
    "keyword_tags": [
      "Verrouillage temporel",
      "Contrats intelligents",
      "Escrow",
      "Automatisation",
      "Vesting"
    ],
    "hash": "512c258c474997a51a8c15493f3d0373038a9535a7c29929fa4c0f2d3d26f65a",
    "last_updated": "2025-06-06"
  },
  {
    "id": "web3-signatures",
    "title": "Signatures Web3",
    "description": "Créez un système où les utilisateurs signent des documents ou des transactions avec leur signature de portefeuille. Stockez les hachages de documents sur la chaîne, et éventuellement sauvegardez les fichiers sur IPFS. D'autres peuvent vérifier l'horodatage, l'identité du signataire et l'intégrité du contenu. Imiter des outils comme DocuSign mais en utilisant une authentification de blockchain qui est décentralisée et résistante à la censure.",
    "status": "idée",
    "complexity_score": 4,
    "effort_score": -1,
    "adoption_score": 3,
    "blockchain_score": 7,
    "revenue_score": -1,
    "industry_tags": [
      "Services",
      "Banques et marchés de capitaux"
    ],
    "keyword_tags": [
      "Signature",
      "Authentification",
      "IPFS",
      "Conformité",
      "Documents"
    ],
    "hash": "765ba8aa306dedb7a04a57f84756bb60a87dfd60ebf161767d31c07b71537e39",
    "last_updated": "2025-06-06"
  }
];

