export interface I18n {
  about_page: {
    title: string;
    sections: {
      heading: string;
      content: string;
    }[];
    team: {
      team_title: string;
      members: {
        name: string;
        role: string;
        image: string;
        description: string[];
      }[];
    };
    back_home: string;
  };
}

export const en: I18n = {
  about_page: {
    title: "What is Monark ?",
    sections: [
      {
        heading: "Introduction",
        content: `Monark is an initiative aimed at creating a collaborative and accessible Web3 ecosystem for university students, developers, entrepreneurs, Web3 enthusiasts, and local communities. It provides a centralized platform to share project ideas, collaborate on open-source applications, and access tailored technical resources.`,
      },
      {
        heading: "Development and Adoption",
        content: `Monark will also participate in the development of several essential modules to facilitate the development and adoption of Web3. We will also offer educational resources in partnership with universities to support new developers and entrepreneurs in their transition to Web3.`,
      },
      {
        heading: "Community Approach",
        content: `The initiative is based on an open and democratic approach, where every community member can participate in the creation and improvement of Web3 tools and services. Through this vision, Monark will facilitate access to next-generation technologies while ensuring that the benefits remain in the hands of users and local communities.`,
      },
      {
        heading: "Why Monark?",
        content: `Web3 presents many challenges that hinder its adoption, including a lack of structure and accessible resources, high development costs, and centralized governance that limits opportunities for local communities.

Monark is designed to address these issues by creating a collaborative and educational platform that simplifies entry into the Web3 ecosystem. By democratizing access to decentralized technologies, Monark enables more people to participate in innovation without having to overcome technical or financial barriers.

Unlike traditional Web3 initiatives, Monark focuses on community governance, profit redistribution, and user autonomy. Instead of concentrating power and profits in the hands of a few actors, the initiative ensures that the resources and revenues generated by the platform are redistributed to the communities that use it.`,
      },
      {
        heading: "Vision",
        content: `To build a resilient, open, and decentralized future where every individual and community can participate in innovation, governance, and value creation.`,
      },
      {
        heading: "Mission",
        content: `Empower local communities, students, and developers by offering the tools, knowledge, and support needed to build and govern decentralized applications and infrastructures.`,
      },
      {
        heading: "Values",
        content: `• Accessibility: Lowering the barrier to entry for all participants.\n• Transparency: Open governance and open-source development.\n• Collaboration: Shared success through community-driven initiatives.\n• Sustainability: Long-term thinking for communities and ecosystems.\n• Innovation: Supporting experimentation and creativity at all levels.`,
      },
    ],
    team: {
      team_title: "The Team",
      members: [
        {
          name: "Vincent Grenier",
          role: "CEO",
          image: "/images/team/vincent-grenier.jpg",
          description: [
            "Studied in civil & structural engineering.",
            "Co-founder and CFO of EOS Nation and Pinax.",
            "VP Finance & Crypto operations at ENF.",
            "Years of experience in the blockchain environment.",
          ],
        },
        {
          name: "Loucas Pelletier",
          role: "COO",
          image: "/images/team/loucas-pelletier.jpg",
          description: [
            "Studied in tech focus management and MBA.",
            "4 years of project management experience.",
            "Managed teams of 10 to 25 employees.",
          ],
        },
        {
          name: "Dominic Fournier",
          role: "CTO",
          image: "/images/team/dominic-fournier.jpg",
          description: [
            "Experience in leading full-stack teams and interns.",
            "Expert in UI/UX.",
            "8 years of experience in product design and frontend development.",
            "Experience in analytics and dashboard creation.",
            "Knowledge of the web3 technology and environment.",
          ],
        },
      ],
    },
    back_home: "Back Home",
  },
};

export const fr: I18n = {
  about_page: {
    title: "Qu'est-ce que Monark ?",
    sections: [
      {
        heading: "Introduction",
        content: `Monark est une initiative qui vise à créer un écosystème Web3 collaboratif et accessible pour les étudiants universitaires, développeurs, entrepreneurs, enthousiaste du web3 et les communautés locales. Elle met à disposition une plateforme centralisée permettant de partager des idées de projet, collaborer sur des applications open-source et accéder à des ressources techniques adaptées.`,
      },
      {
        heading: "Développement et Adoption",
        content: `Monark participera aussi au développement de plusieurs modules essentiels pour faciliter le développement et l'adoption du Web3. Nous proposerons aussi des ressources éducatives en partenariat avec des universités afin d'accompagner les nouveaux développeurs et entrepreneurs dans leur transition vers le Web3.`,
      },
      {
        heading: "Approche Communautaire",
        content: `L'initiative repose sur une approche ouverte et démocratique, où chaque membre de la communauté peut participer à la création et à l'amélioration des outils et services Web3. Grâce à cette vision, Monark facilitera l'accès aux technologies de nouvelle génération tout en assurant que les bénéfices restent entre les mains des utilisateurs et des communautés locales.`,
      },
      {
        heading: "Pourquoi Monark ?",
        content: `Le Web3 présente de nombreux défis qui freinent son adoption, notamment un manque de structuration et de ressources accessibles, des coûts élevés de développement, et une gouvernance centralisée qui limite les opportunités pour les communautés locales.

Monark est conçu pour répondre à ces problématiques en créant une plateforme collaborative et éducative qui simplifie l'entrée dans l'écosystème Web3. En démocratisant l'accès aux technologies décentralisées, Monark permet à davantage de personnes de participer à l'innovation sans avoir à surmonter des barrières techniques ou financières.

Contrairement aux initiatives Web3 traditionnelles, Monark met l'accent sur la gouvernance communautaire, la redistribution des bénéfices et l'autonomie des utilisateurs. Plutôt que de concentrer le pouvoir et les profits entre les mains de quelques acteurs, l'initiative s'assure que les ressources et revenus générés par la plateforme soient redistribués aux communautés qui l'utilisent.`,
      },
      {
        heading: "Vision",
        content: `Construire un avenir résilient, ouvert et décentralisé où chaque individu et chaque communauté peut participer à l'innovation, à la gouvernance et à la création de valeur.`,
      },
      {
        heading: "Mission",
        content: `Donner les moyens aux communautés locales, aux étudiants et aux développeurs en leur offrant les outils, les connaissances et le soutien nécessaires pour construire et gouverner des applications et des infrastructures décentralisées.`,
      },
      {
        heading: "Valeurs",
        content: `• Accessibilité : Réduire les barrières à l'entrée pour tous les participants.\n• Transparence : Gouvernance ouverte et développement open source.\n• Collaboration : Réussite partagée par des initiatives communautaires.\n• Durabilité : Une vision à long terme pour les communautés et les écosystèmes.\n• Innovation : Soutenir l'expérimentation et la créativité à tous les niveaux.`,
      },
    ],
    team: {
      team_title: "L'équipe",
      members: [
        {
          name: "Vincent Grenier",
          role: "PDG",
          image: "/images/team/vincent-grenier.jpg",
          description: [
            "Études en génie civil et structural.",
            "Co-fondateur et directeur financier d'EOS Nation et Pinax.",
            "Vice-président des finances et des opérations crypto à l'ENF.",
            "Plusieurs années d'expérience dans l'environnement blockchain.",
          ],
        },
        {
          name: "Loucas Pelletier",
          role: "Directeur des opérations",
          image: "/images/team/loucas-pelletier.jpg",
          description: [
            "Études en gestion axée sur la technologie et MBA.",
            "4 ans d'expérience en gestion de projet.",
            "Gestion d'équipes de 10 à 25 employés.",
          ],
        },
        {
          name: "Dominic Fournier",
          role: "Directeur technique",
          image: "/images/team/dominic-fournier.jpg",
          description: [
            "Expérience en direction d'équipes complètes et de stagiaires.",
            "Expert en UI/UX.",
            "8 ans d'expérience en conception de produits et développement frontend.",
            "Expérience en analytique et création de tableaux de bord.",
            "Connaissance de la technologie et de l'environnement web3.",
          ],
        },
      ],
    },
    back_home: "Retour à l'accueil",
  },
};
